# Generated by Django 5.1.7 on 2025-03-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=50)),
                ('serial_number', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=25)),
                ('color', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('cert_verification', models.BooleanField(default=False)),
            ],
        ),
    ]
